version: '3.8'

services:
  products-db:
    image: julescruz10015482/products-db-1:latest  # Correctly referencing the pre-built image
    ports:
      - "5432:5432"
    networks:
      - app-net
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 250M
      placement:
        constraints:
          - node.role == manager

  products-api:
    image: julescruz10015482/products-api-1:latest  # Correctly referencing the pre-built image
    environment:
      - PRICE_FACTOR=1.5
    networks:
      - app-net
    depends_on:
      - products-db
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
      placement:
        constraints:
          - node.role == manager

  stock-api:
    image: julescruz10015482/stock-api-1:latest  # Correctly referencing the pre-built image
    networks:
      - app-net
    depends_on:
      - products-db
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.25"
          memory: 100M
      placement:
        constraints:
          - node.role == manager

  web:
    image: julescruz10015482/web-1:latest  # Correctly referencing the pre-built image
    environment:
      - Widgetario__Theme=dark
    volumes:
      - ./config/web:/app/config
      - ./logs/web:/logs
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on:
      - products-api
      - stock-api
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
      placement:
        constraints:
          - node.role == manager

networks:
  app-net:
    driver: overlay  # Use overlay for Swarm mode